site_name: Akagera.jl
repo_url:  https://github.com/lcolaholicl/Akagera.jl
site_description: Documentation for Akagera.jl
site_author: lcolaholicl

theme: readthedocs

extra_css:
- assets/Documenter.css

markdown_extensions:
- extra
- tables
- fenced-code

docs_dir: 'build'

pages:
- Home: index.md
- Library:
  - Animator: lib/animator.md